const P=[
['serein','Serein Tote','canta','Çanta',2890,'Yeni','https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=86'],
['aube','Aube Linen Curtain','perde','Perde',3450,'Atelier','https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1500&q=86'],
['miel','Miel Mini Bag','canta','Çanta',2390,'Az kaldı','https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=1200&q=86'],
['nuit','Nuit Throw','ortu','Örtü',1980,'Bestseller','https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=86'],
['sol','Sol Cushion Set','ev','Ev Tekstili',1690,'Set','https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=86'],
['brume','Brume Sheer','perde','Perde',3150,'Özel Ölçü','https://images.unsplash.com/photo-1564078516393-cf04bd966897?auto=format&fit=crop&w=1200&q=86'],
['terre','Terre Weekender','canta','Çanta',3690,'Yeni','https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=86'],
['halo','Halo Bed Cover','ortu','Örtü',4290,'Limited','https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1200&q=86']];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(n);let cart=JSON.parse(localStorage.getItem('sem-cart')||'{}'),timer;
function cards(){ $('#grid').innerHTML=P.map(p=>`<article class="card reveal" data-cat="${p[2]}"><div class="media"><img src="${p[6]}" alt="${p[1]}" loading="lazy"><span class="badge">${p[5]}</span><button class="add" data-add="${p[0]}" aria-label="Sepete ekle">＋</button></div><div class="meta"><div><h3>${p[1]}</h3><p>${p[3]}</p></div><span class="price">${money(p[4])}</span></div></article>`).join(''); reveal() }
function save(){localStorage.setItem('sem-cart',JSON.stringify(cart))}function qty(){return Object.values(cart).reduce((a,b)=>a+b,0)}function total(){return Object.entries(cart).reduce((s,[id,n])=>s+(P.find(p=>p[0]===id)?.[4]||0)*n,0)}
function drawCart(){let q=qty();$('#cartCount').textContent=q;$('#total').textContent=money(total());$('#empty').style.display=q?'none':'block';$('#cartFoot').style.display=q?'block':'none';$('#cartItems').innerHTML=Object.entries(cart).map(([id,n])=>{let p=P.find(x=>x[0]===id);return `<div class="cartItem"><img src="${p[6]}" alt=""><div><h3>${p[1]}</h3><p>${p[3]}</p><button data-q="-1" data-id="${id}">−</button><span>${n}</span> <button data-q="1" data-id="${id}">＋</button></div><span>${money(p[4]*n)}</span></div>`}).join('')}
function add(id){cart[id]=(cart[id]||0)+1;save();drawCart();toast('SEPETE EKLENDİ')}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('on');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('on'),1600)}
function cartOpen(v){$('#cart').classList.toggle('on',v);$('#backdrop').classList.toggle('on',v);document.body.classList.toggle('lock',v);$('#cart').setAttribute('aria-hidden',String(!v))}function searchOpen(v){$('#search').classList.toggle('on',v);document.body.classList.toggle('lock',v);$('#search').setAttribute('aria-hidden',String(!v));if(v)setTimeout(()=>$('#searchInput').focus(),120)}
function reveal(){let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.1});$$('.reveal:not(.in)').forEach(x=>io.observe(x))}
document.addEventListener('click',e=>{let a=e.target.closest('[data-add]');if(a)add(a.dataset.add);let q=e.target.closest('[data-q]');if(q){cart[q.dataset.id]=(cart[q.dataset.id]||0)+Number(q.dataset.q);if(cart[q.dataset.id]<=0)delete cart[q.dataset.id];save();drawCart()}let r=e.target.closest('[data-result]');if(r){add(r.dataset.result);searchOpen(false);cartOpen(true)}});
$('#cartBtn').onclick=()=>cartOpen(true);$('#cartClose').onclick=$('#backdrop').onclick=()=>cartOpen(false);$('#searchBtn').onclick=()=>searchOpen(true);$('#searchClose').onclick=()=>searchOpen(false);$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.card').forEach(c=>c.classList.toggle('hide',b.dataset.filter!=='all'&&c.dataset.cat!==b.dataset.filter))});
$('#searchInput').oninput=e=>{let q=e.target.value.toLocaleLowerCase('tr-TR').trim();$('#searchResults').innerHTML=q?P.filter(p=>(p[1]+' '+p[3]).toLocaleLowerCase('tr-TR').includes(q)).map(p=>`<button class="result" data-result="${p[0]}"><b>${p[1]}</b><span>${p[3]} · ${money(p[4])} · Sepete ekle</span></button>`).join(''):''};$('#journalForm').onsubmit=e=>{e.preventDefault();$('#journalMsg').textContent='Teşekkürler. Semaison Journal listesine eklendin.';e.target.reset()};$('#checkout').onclick=()=>toast('ÖDEME ALTYAPISI BAĞLANMAYA HAZIR');window.addEventListener('scroll',()=>document.querySelector('header').classList.toggle('sticky',scrollY>innerHeight*.72),{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape'){cartOpen(false);searchOpen(false)}});cards();drawCart();reveal();
